#!/usr/bin/env node
/* Purpose: ui-doc-audit — the UI documentation COMPLETENESS gate + dedup/divergence detector.
 * Doc: docs/internal/code/tools/audit-suite/ui-doc-audit.md */
/* ──────────────────────────────────────────────────────────────────────────
   RedPash ui-doc-audit — auto-discovered by tools/audit.sh (tool name: `ui-doc`).

   Em's requirement: completeness must be GUARANTEED, not curated — a hand list
   silently misses components (the Cases-comments view, modals…). So the DENOMINATOR
   is enumerated from code by tools/lib/fe-inventory.js, and this audit FAILS (exit 1)
   if any enumerated component is not listed in the generated catalog INDEX
   (docs/internal/ui/catalog/index.md). The index is generated by tools/doc-gen
   (kind=component), so it is complete by construction — the gate goes green on
   generation and red only when the index DRIFTS from the code (a component added
   without regenerating). Same idempotence contract as the schema phase. Same
   discipline as doc-coverage-audit (files) + api-doc-audit (routes). UI = backend.

   Finding classes:
     • coverage   (HARD, exit 1) — an enumerated component is missing from the index
                                    (index stale / absent) → regenerate.
     • divergence (advisory)     — one class styled under ≥2 ancestor contexts → unify.
     • parallel   (advisory)     — a role-suffix shared across blocks → compose one atom.
   Advisory findings are work-items (file them); only coverage gates CI, so existing
   dedup debt doesn't wedge the shared suite.

   Read-only. No deps beyond tools/lib/fe-inventory. Emits audit.json + audit.html.
   ────────────────────────────────────────────────────────────────────────── */
'use strict';

var fs = require('fs');
var path = require('path');
var inv = require('../lib/fe-inventory');

var ROOT = path.resolve(__dirname, '..', '..');
var INDEX = path.join(ROOT, 'docs', 'internal', 'ui', 'catalog', 'index.md');
var INDEX_REL = path.relative(ROOT, INDEX);

/* ── coverage: every enumerated component must appear in the generated index ── */
function coverageFindings(components) {
  var text = null;
  try { text = fs.readFileSync(INDEX, 'utf8'); } catch (e) { /* missing */ }
  if (text == null) {
    return [{ kind: 'coverage', severity: 'error', component: '(all)',
      detail: INDEX_REL + ' is missing — run `node tools/doc-gen/gen.js --components`' }];
  }
  var hasRegion = text.indexOf('<!-- doc-gen:component:index ') >= 0;
  var findings = [];
  if (!hasRegion) findings.push({ kind: 'coverage', severity: 'error', component: '(region)',
    detail: INDEX_REL + ' has no doc-gen:component:index generated region — regenerate' });
  components.forEach(function (g) {
    // the index lists each component key in a table cell `| `rp-foo` |` — token presence is enough
    if (text.indexOf(g.key) < 0) findings.push({ kind: 'coverage', severity: 'error',
      component: g.key, classes: g.classes.length, jsRendered: g.jsRendered,
      detail: 'component not listed in the catalog index (stale — regenerate)' });
  });
  return findings;
}

/* ── html report ──────────────────────────────────────────────────────────── */
function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function table(headers, rows) {
  return '<table><tr>' + headers.map(function (h) { return '<th>' + esc(h) + '</th>'; }).join('') + '</tr>' +
    rows.map(function (r) { return '<tr>' + r.map(function (c) {
      return '<td>' + esc(Array.isArray(c) ? c.join(', ') : (c == null ? '' : c)) + '</td>'; }).join('') + '</tr>'; }).join('') +
    '</table>';
}
function html(summary, cov, div, par) {
  return '<!doctype html><meta charset=utf8><title>ui-doc-audit</title>' +
    '<style>body{font:14px/1.5 system-ui;margin:2rem;max-width:80rem}h2{margin-top:2rem}' +
    'table{border-collapse:collapse;width:100%;margin:.5rem 0}td,th{border:1px solid #ccc;padding:.3rem .5rem;text-align:left;vertical-align:top}' +
    '.err{color:#b00}.warn{color:#a60}code{background:#f4f4f4;padding:0 .2rem}</style>' +
    '<h1>ui-doc-audit</h1><p>' + esc(JSON.stringify(summary)) + '</p>' +
    '<h2 class=err>coverage gaps (' + cov.length + ') — hard fail</h2>' +
      table(['component', 'classes', 'detail'], cov.map(function (f) { return [f.component, f.classes, f.detail]; })) +
    '<h2 class=warn>divergence (' + div.length + ') — same name, different behavior</h2>' +
      table(['class', 'contexts'], div.map(function (f) { return ['.' + f.cls, f.contexts]; })) +
    '<h2 class=warn>parallel-class clusters (' + par.length + ') — compose, don\'t parallel</h2>' +
      table(['-suffix', 'blocks', 'count', 'members'], par.map(function (f) { return ['-' + f.suffix, f.blocks, f.count, f.members]; }));
}

/* ── main ─────────────────────────────────────────────────────────────────── */
function main() {
  var a = inv.analyze();
  var cov = coverageFindings(a.components);
  var div = a.divergences, par = a.parallels;

  var summary = {
    components: a.counts.components, hooks: a.counts.hooks, classes: a.counts.classes,
    coverageGaps: cov.length, divergences: div.length, parallelClusters: par.length,
  };
  var stamp = new Date().toISOString().slice(0, 10);
  var findings = cov
    .concat(div.map(function (d) { return { kind: 'divergence', severity: 'warn', cls: d.cls, contexts: d.contexts,
      detail: '`.' + d.cls + '` styled under ' + d.contexts.length + ' contexts' }; }))
    .concat(par.map(function (p) { return { kind: 'parallel', severity: 'warn', suffix: p.suffix, count: p.count,
      blocks: p.blocks, members: p.members, detail: '`-' + p.suffix + '` in ' + p.count + ' classes across ' + p.blocks + ' blocks' }; }));
  fs.writeFileSync(path.join(__dirname, 'audit.json'),
    JSON.stringify({ tool: 'ui-doc', generatedAt: stamp, summary: summary, findings: findings }, null, 2));
  fs.writeFileSync(path.join(__dirname, 'audit.html'), html(summary, cov, div, par));

  console.log('ui-doc-audit');
  console.log('────────────');
  console.log('components:        ' + summary.components + '  (catalog denominator)');
  console.log('dynamic hooks:     ' + summary.hooks);
  console.log('classes:           ' + summary.classes);
  console.log('coverage gaps:     ' + summary.coverageGaps + (summary.coverageGaps ? '  ← FAIL (index stale/missing)' : '  ✓ index complete'));
  console.log('divergences:       ' + summary.divergences + '  (same class, ≥2 ancestor contexts)');
  console.log('parallel clusters: ' + summary.parallelClusters + '  (shared role-suffix across blocks)');
  if (par.length) {
    console.log('\ntop parallel-class clusters (compose → atom):');
    par.slice(0, 8).forEach(function (f) { console.log('  -' + f.suffix + '  ×' + f.count + ' across ' + f.blocks + ' blocks'); });
  }
  console.log('\nreport: ' + path.relative(ROOT, path.join(__dirname, 'audit.html')));
  process.exit(cov.length ? 1 : 0);   // HARD gate: coverage only
}
main();
