-- ──────────── 024 drop users.prefs — Phase 2 of user-prefs migration ────────────
-- Companion to migration 023 (user_preferences). Drops the now-dead
-- `users.prefs` JSONB column — all reads route through the
-- `user_preferences` table (via the jsonb_object_agg subquery the
-- user-read queries in db.rs use), all writes go through
-- `patch_user_prefs(…)` called from `PATCH /api/me/prefs` (and from
-- the deprecation-forward path on `PATCH /api/me`).
--
-- Phase-2 safe at this point because:
--   1. Mig 023 already copied every row's prefs JSONB into
--      user_preferences. The data is preserved.
--   2. update_user dropped the `prefs = prefs || …` SET clause in
--      ba41140; nothing has written to users.prefs since.
--   3. Every find/list/insert/upsert query in db.rs sources `prefs`
--      from the subquery — verified by `grep users.prefs` (only
--      hits are explanatory comments, which this commit also
--      cleans up per [[keep-comments-truthful]]).
--
-- Spec: docs/internal/spec-user-preferences.md §3 (migration of
-- existing data) + §7.1 (drop on Em's call, locked 2026-05-23).
--
-- Idempotent via IF EXISTS so a manual psql apply and the later
-- sqlx::migrate! pass at backend boot don't collide.

ALTER TABLE users DROP COLUMN IF EXISTS prefs;
