{
  "type": "record",
  "name": "Account",
  "namespace": "example",
  "fields": [
    {
      "name": "accountId",
      "type": "string"
    },
    {
      "name": "accountType",
      "type": "string"
    },
    {
      "name": "title",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "namePrefix",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "firstName",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "middleName",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "lastName",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "additionalLastName",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "academicTitle",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "nonAcademicTitle",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "dateOfBirth",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "employerName",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "organisationName1",
      "type": "string"
    },
    {
      "name": "organisationName2",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "preferredLanguage",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "preferredContactMethod",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "preferredContactTime",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "accountOrigin",
      "type": "string"
    },
    {
      "name": "gender",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "country",
      "type": "string"
    },
    {
      "name": "generation",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "telephone",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "TelephoneEntry",
          "fields": [
            {
              "name": "phoneNumber",
              "type": "string"
            },
            {
              "name": "phoneNumberType",
              "type": "string"
            },
            {
              "name": "PhoneNumberExtension",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "country",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "doNotUseFlag",
              "type": {
                "type": "int",
                "arg.properties": {
                  "options": [
                    0,
                    1
                  ]
                }
              }
            },
            {
              "name": "actionCode",
              "type": "string"
            },
            {
              "name": "actionDesc",
              "type": "string"
            }
          ]
        }
      }
    },
    {
      "name": "email",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "EmailEntry",
          "fields": [
            {
              "name": "emailAddress",
              "type": "string"
            },
            {
              "name": "doNotUseFlag",
              "type": {
                "type": "int",
                "arg.properties": {
                  "options": [
                    0,
                    1
                  ]
                }
              }
            },
            {
              "name": "actionCode",
              "type": "string"
            },
            {
              "name": "actionDesc",
              "type": "string"
            }
          ]
        }
      }
    },
    {
      "name": "accountRole",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "AccountRoleEntry",
          "fields": [
            {
              "name": "role",
              "type": "string"
            },
            {
              "name": "actionCode",
              "type": "string"
            },
            {
              "name": "actionDesc",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        }
      }
    },
    {
      "name": "accountAddress",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "AccountAddressEntry",
          "fields": [
            {
              "name": "addressType",
              "type": "string"
            },
            {
              "name": "address",
              "type": {
                "type": "record",
                "name": "PostalAddress",
                "fields": [
                  {
                    "name": "poBox",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "premiseNumber",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "building",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "buildingFloor",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "street",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "supplement1",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "supplement2",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "supplement3",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "cityTown",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "regionState",
                    "type": [
                      "null",
                      "string"
                    ]
                  },
                  {
                    "name": "postcodeZip",
                    "type": "string"
                  },
                  {
                    "name": "country",
                    "type": "string"
                  }
                ]
              }
            }
          ]
        }
      }
    }
  ]
}
