// MCP-Cases bridge — thin HTTP client wrapping the canonical
// /api/cases routes. Each MCP tool's callTool branch goes through a
// helper here; the helpers don't add policy, just config + path +
// JSON shape. The Rust backend owns auth, RBAC, audit-events,
// invariant validation — the bridge is a transport adapter.
//
// Auth model (v1, dev-permissive per [[redpash-stage]]):
//   REDPASH_API_BASE     — base URL incl. /api suffix.
//                          Default: http://localhost:8080/api
//   REDPASH_API_SESSION  — rp_session cookie value. Required for any
//                          tool call that hits an auth-gated endpoint
//                          (all of them today). Generated by the
//                          canonical host once and pinned in env.
//
// The bridge is per-agent in stdio mode (one subprocess per Claude
// Code instance, env scoped per process), so the session identity
// IS the agent's identity. HTTP-transport mode would need explicit
// agent identity per call — out of scope for v1; the same env-pin
// works for the single canonical-host case the bridge was scoped for.

const API_BASE_DEFAULT = "http://localhost:8080/api";

export class CaseApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public body?: unknown,
  ) {
    super(message);
    this.name = "CaseApiError";
  }
}

function apiBase(): string {
  return (process.env.REDPASH_API_BASE ?? API_BASE_DEFAULT).replace(/\/+$/, "");
}

function sessionCookie(): string | null {
  const sid = process.env.REDPASH_API_SESSION;
  return sid ? `rp_session=${sid}` : null;
}

interface ApiOpts {
  method?: "GET" | "POST" | "PATCH" | "DELETE";
  body?: unknown;
  query?: Record<string, string | undefined>;
}

async function apiFetch<T = unknown>(path: string, opts: ApiOpts = {}): Promise<T> {
  const method = opts.method ?? "GET";
  let url = apiBase() + path;
  if (opts.query) {
    const params = new URLSearchParams();
    for (const [k, v] of Object.entries(opts.query)) {
      if (v != null && v !== "") params.set(k, v);
    }
    const qs = params.toString();
    if (qs) url += (url.includes("?") ? "&" : "?") + qs;
  }
  const headers: Record<string, string> = { Accept: "application/json" };
  const cookie = sessionCookie();
  if (cookie) headers.Cookie = cookie;
  if (opts.body !== undefined) headers["Content-Type"] = "application/json";

  const res = await fetch(url, {
    method,
    headers,
    body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
  });
  const ct = res.headers.get("content-type") ?? "";
  let parsed: unknown = null;
  if (ct.includes("application/json")) {
    try { parsed = await res.json(); } catch { parsed = null; }
  } else {
    try { parsed = await res.text(); } catch { parsed = null; }
  }
  if (!res.ok) {
    const msg = typeof parsed === "object" && parsed && "message" in (parsed as object)
      ? String((parsed as Record<string, unknown>).message)
      : `${method} ${path} failed with HTTP ${res.status}`;
    throw new CaseApiError(msg, res.status, parsed);
  }
  return parsed as T;
}

// ── tool-shape DTOs (mirror the Rust handlers' request/response) ────

export interface CaseCreateArgs {
  title: string;
  description?: string;
  type?: "bug" | "feature" | "task" | "epic";
  priority?: "low" | "medium" | "high" | "critical";
  assignee_id?: string;
  project_id?: string;
  company_id?: string;
}

export interface CaseCommentArgs {
  rid: string;
  body: string;
}

export interface CaseListArgs {
  status?: string;
  assignee?: string;
  project?: string;
  q?: string;
  page?: number;
  size?: number;
}

export interface CaseSummary {
  redpash_id?: string;
  title?: string;
  status?: string;
  priority?: string;
  type?: string;
  assignee_id?: string | null;
  assignee_display_name?: string | null;
  reporter_id?: string | null;
  reporter_display_name?: string | null;
  updated_at?: string;
  created_at?: string;
  [k: string]: unknown;
}

// ── public helpers ──────────────────────────────────────────────────

export function createCase(args: CaseCreateArgs) {
  return apiFetch<CaseSummary>("/cases", { method: "POST", body: args });
}

export function getCase(rid: string) {
  return apiFetch<unknown>(`/cases/${encodeURIComponent(rid)}`);
}

export function listCases(args: CaseListArgs) {
  return apiFetch<{ items: CaseSummary[]; total: number; page: number; size: number }>(
    "/cases",
    {
      query: {
        status:   args.status,
        assignee: args.assignee,
        project:  args.project,
        q:        args.q,
        page:     args.page != null ? String(args.page) : undefined,
        size:     args.size != null ? String(args.size) : undefined,
      },
    },
  );
}

export function addComment(args: CaseCommentArgs) {
  return apiFetch<unknown>(
    `/cases/${encodeURIComponent(args.rid)}/comments`,
    { method: "POST", body: { body: args.body } },
  );
}
